services:
  # 1. PYTHON UYGULAMAMIZ (Yeni Eklenen Kısım)
  app:
    build: .  # Dockerfile'ı olduğu dizinden (buradan) inşa et
    container_name: nexstream_engine
    depends_on:
      - db  # Veritabanı açılmadan ben açılmam
    # YENİ KOMUT: Uvicorn sunucusunu başlatıyoruz
    # --host 0.0.0.0: Dışarıdan gelen isteklere cevap ver
    # --reload: Kod değişirse sunucuyu yeniden başlat (Geliştirme modu)
    # Yeni komutumuz bu: src klasöründeki main.py içindeki 'app' nesnesini çalıştır.
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      # DİKKAT: .env dosyasındaki 127.0.0.1 ayarını burada eziyoruz.
      # Konteynır içinden veritabanına "db" ismiyle ulaşılır.
      - DB_HOST=db
      - DB_PORT=5432 # İçeride port 5432'dir (Dışarıdaki 5433 değil!)
      # Diğer şifreleri .env dosyasından otomatik okur
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    ports:
      - "8000:8000"  # Bilgisayarının 8000 portunu konteynırın 8000'ine bağla  
    volumes:
      # Canlı Güncelleme (Hot Reload):
      # Bilgisayarındaki kod değişirse, konteynırın içindeki de değişsin.
      - .:/app

  # 2. VERİTABANI (PostgreSQL)
  db:
    image: postgres:15-alpine
    container_name: nexstream_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432" # 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 3. YÖNETİM PANELİ (Adminer)
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

  # 4. KAFKA KOORDİNATÖRÜ (Zookeeper)
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: nexstream_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  # 5. MESAJ KUYRUĞU (Kafka Broker)
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: nexstream_kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # Kafka'nın dış dünya ve iç dünya ile nasıl konuşacağı ayarı (Biraz karmaşıktır ama standarttır)
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # 6. ARKA PLAN İŞÇİSİ (Consumer)
  worker:
    build: . # App ile aynı imajı kullanır (Tekrar build etmez, hızlıdır)
    container_name: nexstream_worker
    depends_on:
      - kafka
      - db
    # KRİTİK NOKTA: App servisi "uvicorn" çalıştırırken, bu servis "consumer" çalıştırır.
    command: python -m src.adapters.messaging.kafka_consumer
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    volumes:
      - .:/app

  # 7. ZAMANLAYICI (Scheduler)
  scheduler:
    build: .
    container_name: nexstream_scheduler
    depends_on:
      - kafka
    command: python src/adapters/scheduling/scheduler_service.py
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    volumes:
      - .:/app

volumes:
  postgres_data: